package domain

import (
	"github.com/MohammedKamle/banking/errs"
	"github.com/MohammedKamle/banking/logger"
	"github.com/jmoiron/sqlx"
	"strconv"
)

type AccountRepositoryDb struct {
	client *sqlx.DB
}

func (d AccountRepositoryDb) Save(account Account) (*Account, *errs.AppError) {
	// not inserting account_id as it will be automatically generated by the db
	sqlInsert := "INSERT INTO accounts (customer_id, opening_date, account_type, amount, status) values (?,?,?,?,?)"
	result, err := d.client.Exec(sqlInsert, account.CustomerId, account.OpeningDate,
		account.AccountType, account.Amount, account.Status)
	if err != nil {
		logger.Error("Error while creating new account " + err.Error())
		return nil, errs.NewUnexpectedError("unexpected error from database")
	}
	// LastInsertId will give the last inserted row id which we will then assign to our domain account on line 29
	id, err := result.LastInsertId()
	if err != nil {
		logger.Error("Error while creating new account " + err.Error())
		return nil, errs.NewUnexpectedError("unexpected error from database")
	}
	account.AccountId = strconv.FormatInt(id, 10)
	return &account, nil
}

func NewAccountRepositoryDb(dbClient *sqlx.DB) AccountRepositoryDb {
	return AccountRepositoryDb{dbClient}
}
